=== mlcommons/mobile_app_open/tools/extended-result.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/ExtendedResultSchema",
    "definitions": {
        "ExtendedResultSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "meta": {
                    "$ref": "#/definitions/Meta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Result"
                    }
                },
                "environment_info": {
                    "$ref": "#/definitions/EnvironmentInfo"
                },
                "build_info": {
                    "$ref": "#/definitions/BuildInfo"
                }
            },
            "required": [
                "build_info",
                "environment_info",
                "meta",
                "results"
            ],
            "title": "ExtendedResultSchema"
        },
        "BuildInfo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "version": {
                    "type": "string"
                },
                "build_number": {
                    "type": "string"
                },
                "build_date": {
                    "type": "string",
                    "format": "date-time"
                },
                "official_release_flag": {
                    "type": "boolean"
                },
                "dev_test_flag": {
                    "type": "boolean"
                },
                "backend_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "git_branch": {
                    "type": "string"
                },
                "git_commit": {
                    "type": "string"
                },
                "git_dirty_flag": {
                    "type": "boolean"
                }
            },
            "required": [
                "backend_list",
                "build_date",
                "build_number",
                "dev_test_flag",
                "git_branch",
                "git_commit",
                "git_dirty_flag",
                "official_release_flag",
                "version"
            ],
            "title": "BuildInfo"
        },
        "EnvironmentInfo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "platform": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/Value"
                }
            },
            "required": [
                "platform",
                "value"
            ],
            "title": "EnvironmentInfo"
        },
        "Value": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "android": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Android"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "ios": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Ios"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "windows": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Windows"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "required": [
                "android",
                "ios",
                "windows"
            ],
            "title": "Value"
        },
        "Android": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "os_version": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model_code": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "board_code": {
                    "type": "string"
                },
                "proc_cpuinfo_soc_name": {
                    "type": "string"
                },
                "props": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Prop"
                    }
                }
            },
            "required": [
                "board_code",
                "manufacturer",
                "model_code",
                "model_name",
                "os_version",
                "proc_cpuinfo_soc_name",
                "props"
            ],
            "title": "Android"
        },
        "Prop": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "type",
                "value"
            ],
            "title": "Prop"
        },
        "Ios": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "os_version": {
                    "type": "string"
                },
                "model_code": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "soc_name": {
                    "type": "string"
                }
            },
            "required": [
                "model_code",
                "model_name",
                "os_version",
                "soc_name"
            ],
            "title": "Ios"
        },
        "Windows": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "os_version": {
                    "type": "string"
                },
                "cpu_full_name": {
                    "type": "string"
                }
            },
            "required": [
                "cpu_full_name",
                "os_version"
            ],
            "title": "Windows"
        },
        "Meta": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "uuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "creation_date": {
                    "type": "string",
                    "format": "date-time"
                },
                "upload_date": {
                    "format": "date-time",
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "required": [
                "creation_date",
                "upload_date",
                "uuid"
            ],
            "title": "Meta"
        },
        "Result": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "benchmark_id": {
                    "type": "string"
                },
                "benchmark_name": {
                    "type": "string"
                },
                "loadgen_scenario": {
                    "type": "string"
                },
                "backend_settings": {
                    "$ref": "#/definitions/BackendSettings"
                },
                "performance_run": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Run"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "accuracy_run": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Run"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "min_duration": {
                    "type": "number"
                },
                "min_samples": {
                    "type": "integer"
                },
                "backend_info": {
                    "$ref": "#/definitions/BackendInfo"
                }
            },
            "required": [
                "accuracy_run",
                "backend_info",
                "backend_settings",
                "benchmark_id",
                "benchmark_name",
                "loadgen_scenario",
                "min_duration",
                "min_samples",
                "performance_run"
            ],
            "title": "Result"
        },
        "Run": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "throughput": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Throughput"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "accuracy": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Accuracy"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "accuracy2": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/Accuracy"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "dataset": {
                    "$ref": "#/definitions/Dataset"
                },
                "measured_duration": {
                    "type": "number"
                },
                "measured_samples": {
                    "type": "integer"
                },
                "start_datetime": {
                    "type": "string"
                },
                "loadgen_info": {
                    "oneOf": [
                        {
                            "$ref": "#/definitions/LoadgenInfo"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "required": [
                "accuracy",
                "accuracy2",
                "dataset",
                "loadgen_info",
                "measured_duration",
                "measured_samples",
                "start_datetime",
                "throughput"
            ],
            "title": "Run"
        },
        "Accuracy": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "normalized": {
                    "type": "number"
                },
                "formatted": {
                    "type": "string"
                }
            },
            "required": [
                "formatted",
                "normalized"
            ],
            "title": "Accuracy"
        },
        "Dataset": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "data_path": {
                    "type": "string"
                },
                "groundtruth_path": {
                    "type": "string"
                }
            },
            "required": [
                "data_path",
                "groundtruth_path",
                "name",
                "type"
            ],
            "title": "Dataset"
        },
        "LoadgenInfo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "validity": {
                    "type": "boolean"
                },
                "duration": {
                    "type": "number"
                }
            },
            "required": [
                "duration",
                "validity"
            ],
            "title": "LoadgenInfo"
        },
        "Throughput": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "number"
                }
            },
            "required": [
                "value"
            ],
            "title": "Throughput"
        },
        "BackendInfo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "filename": {
                    "type": "string"
                },
                "vendor_name": {
                    "type": "string"
                },
                "backend_name": {
                    "type": "string"
                },
                "accelerator_name": {
                    "type": "string"
                }
            },
            "required": [
                "accelerator_name",
                "backend_name",
                "filename",
                "vendor_name"
            ],
            "title": "BackendInfo"
        },
        "BackendSettings": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "accelerator_code": {
                    "type": "string"
                },
                "accelerator_desc": {
                    "type": "string"
                },
                "framework": {
                    "type": "string"
                },
                "model_path": {
                    "type": "string"
                },
                "batch_size": {
                    "type": "integer"
                },
                "extra_settings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExtraSetting"
                    }
                }
            },
            "required": [
                "accelerator_code",
                "accelerator_desc",
                "batch_size",
                "extra_settings",
                "framework",
                "model_path"
            ],
            "title": "BackendSettings"
        },
        "ExtraSetting": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string",
                    "format": "integer"
                },
                "value_name": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "id",
                "name",
                "value",
                "value_name"
            ],
            "title": "ExtraSetting"
        }
    }
}

=== mlcommons/mobile_app_open/flutter_common/test/data/result_sample.json
{
  "meta": {
    "uuid": "19b74406-569b-4b00-b9e9-6a1df9d4a8e9",
    "creation_date": "2022-12-09T08:07:13.066718Z",
    "upload_date": "2022-12-09T08:07:13.066719Z"
  },
  "results": [
    {
      "benchmark_id": "id",
      "benchmark_name": "name",
      "loadgen_scenario": "SingleStream",
      "backend_settings": {
        "accelerator_code": "",
        "accelerator_desc": "",
        "framework": "",
        "model_path": "",
        "batch_size": 0,
        "extra_settings": [
          {
            "id": "shards_num",
            "name": "Shards number",
            "value": "2",
            "value_name": "2"
          }
        ]
      },
      "performance_run": {
        "throughput": 123.45,
        "accuracy": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "accuracy2": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "dataset": {
          "name": "Imagenet classification validation set",
          "type": "IMAGENET",
          "data_path": "mlperf_datasets/imagenet/img",
          "groundtruth_path": "mlperf_datasets/imagenet/imagenet_val_full.txt"
        },
        "measured_duration": 123.456,
        "measured_samples": 8,
        "start_datetime": "2022-12-09T15:07:13.070330",
        "loadgen_info": {
          "validity": true,
          "duration": 10.6
        }
      },
      "accuracy_run": {
        "throughput": 123.45,
        "accuracy": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "accuracy2": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "dataset": {
          "name": "Imagenet classification validation set",
          "type": "IMAGENET",
          "data_path": "mlperf_datasets/imagenet/img",
          "groundtruth_path": "mlperf_datasets/imagenet/imagenet_val_full.txt"
        },
        "measured_duration": 123.456,
        "measured_samples": 8,
        "start_datetime": "2022-12-09T15:07:13.070407",
        "loadgen_info": {
          "validity": true,
          "duration": 10.6
        }
      },
      "min_duration": 10.5,
      "min_samples": 8,
      "backend_info": {
        "filename": "tflite",
        "vendor_name": "tflite",
        "backend_name": "libtflitebackend",
        "accelerator_name": "accelerator"
      }
    },
    {
      "benchmark_id": "id",
      "benchmark_name": "name",
      "loadgen_scenario": "SingleStream",
      "backend_settings": {
        "accelerator_code": "",
        "accelerator_desc": "",
        "framework": "",
        "model_path": "",
        "batch_size": 0,
        "extra_settings": [
          {
            "id": "shards_num",
            "name": "Shards number",
            "value": "2",
            "value_name": "2"
          }
        ]
      },
      "performance_run": {
        "throughput": 123.45,
        "accuracy": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "accuracy2": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "dataset": {
          "name": "Imagenet classification validation set",
          "type": "IMAGENET",
          "data_path": "mlperf_datasets/imagenet/img",
          "groundtruth_path": "mlperf_datasets/imagenet/imagenet_val_full.txt"
        },
        "measured_duration": 123.456,
        "measured_samples": 8,
        "start_datetime": "2022-12-09T15:07:13.071638",
        "loadgen_info": {
          "validity": true,
          "duration": 10.6
        }
      },
      "accuracy_run": {
        "throughput": 123.45,
        "accuracy": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "accuracy2": {
          "normalized": 0.123,
          "formatted": "12.3%"
        },
        "dataset": {
          "name": "Imagenet classification validation set",
          "type": "IMAGENET",
          "data_path": "mlperf_datasets/imagenet/img",
          "groundtruth_path": "mlperf_datasets/imagenet/imagenet_val_full.txt"
        },
        "measured_duration": 123.456,
        "measured_samples": 8,
        "start_datetime": "2022-12-09T15:07:13.071638",
        "loadgen_info": {
          "validity": true,
          "duration": 10.6
        }
      },
      "min_duration": 10.5,
      "min_samples": 8,
      "backend_info": {
        "filename": "tflite",
        "vendor_name": "tflite",
        "backend_name": "libtflitebackend",
        "accelerator_name": "accelerator"
      }
    }
  ],
  "environment_info": {
    "platform": "android",
    "value": {
      "android": {
        "os_version": "",
        "manufacturer": "",
        "model_code": "",
        "model_name": "",
        "board_code": "",
        "proc_cpuinfo_soc_name": "",
        "props": [
          {
            "type": "socName",
            "name": "",
            "value": ""
          }
        ]
      },
      "ios": {
        "os_version": "",
        "model_code": "",
        "model_name": "",
        "soc_name": ""
      },
      "windows": {
        "os_version": "",
        "cpu_full_name": ""
      }
    }
  },
  "build_info": {
    "version": "1.0",
    "build_number": "10qwe",
    "build_date": "2022-12-09T15:07:13.069544",
    "official_release_flag": false,
    "dev_test_flag": true,
    "backend_list": [
      "libtflitebackend"
    ],
    "git_branch": "feature",
    "git_commit": "as91230jr90qwe",
    "git_dirty_flag": false
  }
}
